.TH bpmtap 1 "Mar 2016" "Version 1.0" MEG

.SH NAME
bpmtap - tap keyboard to find a song's beats-per-minute

.SH SYNOPSIS
Any key will do, use 'q' to quit

.SH DESCRIPTION
Just tap along with the beat of a song, using any key on the keyboard.
bpmtap will show you the time interval in-between taps and the estimated
BPM.

.SH OPTIONS
-h    Help

-v    Version

.SH BUGS
None discovered, so far

.SH AUTHOR
Marc Groenewegen, 2016

.SH SEE ALSO
https://github.com/marcdinkum

